# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"

# NuGet packages in the csproj files
  - package-ecosystem: "nuget" # See documentation for possible values
    directories:
      - "/working/templates/*solution"
      - "/working/templates/*-project"
    schedule:
      interval: "daily"
    ignore:
      # DevPacks represents the DMA on which to compile. Doesn't make sense to always be on the latest version.
      - dependency-name: "Skyline.DataMiner.Files.*"
      - dependency-name: "Skyline.DataMiner.Dev.*"
      - dependency-name: "Skyline.DataMiner.Sdk" # Will be done separately 

# Specifically global.json
  - package-ecosystem: "nuget" # See documentation for possible values
    directories:
      - "/working/templates/SharedItems/OnSolutionLevel"
    schedule:
      interval: "daily"